# Generated by Django 2.0.2 on 2018-03-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Component')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks.Drink')),
            ],
        ),
    ]
