# Generated by Django 2.0.2 on 2018-03-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
